"""内置口语表达需求集：覆盖在国外生活、学习、工作的高频沟通场景。

规则：
1. 每条需求只表达一个具体意图，能拆开的必须拆开（如“少盐/少糖/去冰/少冰/正常冰”）。
2. 每个条目的正面都标明说话对象（对谁说的），AI 据此选择语气和称呼。
3. 每个条目：id（稳定英文 slug）、category（分类）、target（说话对象）、
   raw（原始需求）、front（正面 = 对{target}说：{raw}）。
"""

from __future__ import annotations

# 口语卡默认专名：AI 生成英文表达时，遇到泛称的人/地（朋友、老师、图书馆、
# 车站等）就使用这些默认名，保证表达完整不空着；必须由学习者自己填的
# 空位用【name】/【place】占位。
DEFAULT_PERSON_NAME = "Alex"
DEFAULT_PLACE = "City Library"
DEFAULT_CONTEXT_LABEL = f"默认人名 {DEFAULT_PERSON_NAME} · 默认地名 {DEFAULT_PLACE}"

NEEDS: list[dict[str, str]] = [
    {"id": "daily-greet-formal", "category": "日常寒暄", "target": "新认识的人", "raw": "初次见面打招呼并介绍自己（正式场合）", "front": "对新认识的人说：初次见面打招呼并介绍自己（正式场合）"},
    {"id": "daily-greet-casual", "category": "日常寒暄", "target": "新认识的人", "raw": "初次见面打招呼并介绍自己（同学/朋友场合）", "front": "对新认识的人说：初次见面打招呼并介绍自己（同学/朋友场合）"},
    {"id": "daily-how-are-you", "category": "日常寒暄", "target": "朋友", "raw": "问对方最近怎么样（朋友间）", "front": "对朋友说：问对方最近怎么样（朋友间）"},
    {"id": "daily-reply-how-are-you", "category": "日常寒暄", "target": "朋友", "raw": "回应“最近怎么样”并反问对方", "front": "对朋友说：回应“最近怎么样”并反问对方"},
    {"id": "daily-long-time-no-see", "category": "日常寒暄", "target": "朋友", "raw": "好久不见，表达惊喜", "front": "对朋友说：好久不见，表达惊喜"},
    {"id": "daily-small-talk-weather", "category": "日常寒暄", "target": "朋友", "raw": "用天气开启闲聊", "front": "对朋友说：用天气开启闲聊"},
    {"id": "daily-compliment-complexion", "category": "日常寒暄", "target": "朋友", "raw": "夸对方气色好", "front": "对朋友说：夸对方气色好"},
    {"id": "daily-compliment-haircut", "category": "日常寒暄", "target": "朋友", "raw": "夸对方新发型好看", "front": "对朋友说：夸对方新发型好看"},
    {"id": "daily-ask-weekend", "category": "日常寒暄", "target": "朋友", "raw": "问对方周末过得怎么样", "front": "对朋友说：问对方周末过得怎么样"},
    {"id": "daily-keep-in-touch", "category": "日常寒暄", "target": "朋友", "raw": "说“有空多联系”", "front": "对朋友说：说“有空多联系”"},
    {"id": "daily-run-into", "category": "日常寒暄", "target": "熟人", "raw": "偶遇熟人，简单寒暄后礼貌离开", "front": "对熟人说：偶遇熟人，简单寒暄后礼貌离开"},
    {"id": "daily-introduce-friend", "category": "日常寒暄", "target": "对方", "raw": "把朋友介绍给另一个人", "front": "对对方说：把朋友介绍给另一个人"},
    {"id": "daily-ask-name", "category": "日常寒暄", "target": "新认识的人", "raw": "礼貌询问对方的名字（社交场合）", "front": "对新认识的人说：礼貌询问对方的名字（社交场合）"},
    {"id": "daily-ask-where-from", "category": "日常寒暄", "target": "新认识的人", "raw": "问对方从哪里来（认识新朋友）", "front": "对新认识的人说：问对方从哪里来（认识新朋友）"},
    {"id": "daily-ask-job", "category": "日常寒暄", "target": "新认识的人", "raw": "问对方做什么工作（认识新朋友）", "front": "对新认识的人说：问对方做什么工作（认识新朋友）"},
    {"id": "daily-small-talk-food", "category": "日常寒暄", "target": "朋友", "raw": "用“这附近有什么好吃的”开启闲聊", "front": "对朋友说：用“这附近有什么好吃的”开启闲聊"},
    {"id": "campus-ask-teacher", "category": "校园学习", "target": "老师", "raw": "课后向老师提问（礼貌）", "front": "对老师说：课后向老师提问（礼貌）"},
    {"id": "campus-homework-deadline", "category": "校园学习", "target": "同学", "raw": "问作业截止时间", "front": "对同学说：问作业截止时间"},
    {"id": "campus-essay-deadline", "category": "校园学习", "target": "同学", "raw": "问论文截止时间", "front": "对同学说：问论文截止时间"},
    {"id": "campus-homework-extension", "category": "校园学习", "target": "同学", "raw": "请求延长作业期限并说明理由", "front": "对同学说：请求延长作业期限并说明理由"},
    {"id": "campus-essay-extension", "category": "校园学习", "target": "同学", "raw": "请求延长论文期限并说明理由", "front": "对同学说：请求延长论文期限并说明理由"},
    {"id": "campus-ask-missed", "category": "校园学习", "target": "同学", "raw": "问同学请假落下的内容", "front": "对同学说：问同学请假落下的内容"},
    {"id": "campus-borrow-notes", "category": "校园学习", "target": "同学", "raw": "向同学借笔记", "front": "对同学说：向同学借笔记"},
    {"id": "campus-join-group", "category": "校园学习", "target": "同学", "raw": "请求加入学习小组", "front": "对同学说：请求加入学习小组"},
    {"id": "campus-study-session", "category": "校园学习", "target": "同学", "raw": "约同学一起复习备考", "front": "对同学说：约同学一起复习备考"},
    {"id": "campus-office-hours", "category": "校园学习", "target": "教授", "raw": "约教授办公室时间面谈", "front": "对教授说：约教授办公室时间面谈"},
    {"id": "campus-clarify-assignment", "category": "校园学习", "target": "同学", "raw": "确认作业具体要求（不太明白）", "front": "对同学说：确认作业具体要求（不太明白）"},
    {"id": "campus-present", "category": "校园学习", "target": "同学", "raw": "课堂展示的开场白", "front": "对同学说：课堂展示的开场白"},
    {"id": "campus-scholarship", "category": "校园学习", "target": "教务人员", "raw": "咨询奖学金申请", "front": "对教务人员说：咨询奖学金申请"},
    {"id": "campus-funding", "category": "校园学习", "target": "教务人员", "raw": "咨询助学金或资助申请", "front": "对教务人员说：咨询助学金或资助申请"},
    {"id": "campus-library-help", "category": "校园学习", "target": "图书管理员", "raw": "在图书馆请工作人员帮忙找资料", "front": "对图书管理员说：在图书馆请工作人员帮忙找资料"},
    {"id": "campus-borrow-period", "category": "校园学习", "target": "图书管理员", "raw": "问借书能借多久", "front": "对图书管理员说：问借书能借多久"},
    {"id": "campus-renew-book", "category": "校园学习", "target": "图书管理员", "raw": "续借图书馆的书", "front": "对图书管理员说：续借图书馆的书"},
    {"id": "campus-thanks-lecture", "category": "校园学习", "target": "老师", "raw": "课后向老师道谢", "front": "对老师说：课后向老师道谢"},
    {"id": "campus-group-disagree", "category": "校园学习", "target": "同学", "raw": "小组作业中表达不同意见（不伤和气）", "front": "对同学说：小组作业中表达不同意见（不伤和气）"},
    {"id": "campus-classroom-location", "category": "校园学习", "target": "工作人员", "raw": "问教室或教学楼在哪", "front": "对工作人员说：问教室或教学楼在哪"},
    {"id": "campus-library-hours", "category": "校园学习", "target": "图书管理员", "raw": "问图书馆开放时间", "front": "对图书管理员说：问图书馆开放时间"},
    {"id": "campus-teacher-hours", "category": "校园学习", "target": "老师", "raw": "问老师的办公时间", "front": "对老师说：问老师的办公时间"},
    {"id": "campus-course-enroll", "category": "校园学习", "target": "教务人员", "raw": "咨询怎么选课", "front": "对教务人员说：咨询怎么选课"},
    {"id": "campus-course-drop", "category": "校园学习", "target": "教务人员", "raw": "咨询怎么退课", "front": "对教务人员说：咨询怎么退课"},
    {"id": "work-introduce", "category": "工作职场", "target": "新同事", "raw": "入职或新同事场合做自我介绍", "front": "对新同事说：入职或新同事场合做自我介绍"},
    {"id": "work-ask-help", "category": "工作职场", "target": "同事", "raw": "请同事帮忙（客气）", "front": "对同事说：请同事帮忙（客气）"},
    {"id": "work-offer-help", "category": "工作职场", "target": "同事", "raw": "主动提出帮同事", "front": "对同事说：主动提出帮同事"},
    {"id": "work-ask-priority", "category": "工作职场", "target": "领导", "raw": "手上有几件事，问先做哪个", "front": "对领导说：手上有几件事，问先做哪个"},
    {"id": "work-report-progress", "category": "工作职场", "target": "领导", "raw": "简洁汇报工作进展", "front": "对领导说：简洁汇报工作进展"},
    {"id": "work-more-time", "category": "工作职场", "target": "领导", "raw": "请求更多时间完成任务", "front": "对领导说：请求更多时间完成任务"},
    {"id": "work-clarify-task", "category": "工作职场", "target": "领导", "raw": "确认任务的具体要求", "front": "对领导说：确认任务的具体要求"},
    {"id": "work-schedule-meeting", "category": "工作职场", "target": "同事", "raw": "约一个会议时间", "front": "对同事说：约一个会议时间"},
    {"id": "work-reschedule-meeting", "category": "工作职场", "target": "同事", "raw": "请求把会议改期", "front": "对同事说：请求把会议改期"},
    {"id": "work-decline-overtime", "category": "工作职场", "target": "领导", "raw": "委婉拒绝加班", "front": "对领导说：委婉拒绝加班"},
    {"id": "work-decline-extra", "category": "工作职场", "target": "领导", "raw": "委婉拒绝额外任务", "front": "对领导说：委婉拒绝额外任务"},
    {"id": "work-ask-salary", "category": "工作职场", "target": "HR", "raw": "询问薪资范围（面试或入职）", "front": "对HR说：询问薪资范围（面试或入职）"},
    {"id": "work-ask-benefits", "category": "工作职场", "target": "HR", "raw": "询问福利待遇", "front": "对HR说：询问福利待遇"},
    {"id": "work-day-off", "category": "工作职场", "target": "领导", "raw": "请假", "front": "对领导说：请假"},
    {"id": "work-flex-time", "category": "工作职场", "target": "领导", "raw": "申请调休或弹性时间", "front": "对领导说：申请调休或弹性时间"},
    {"id": "work-ask-feedback", "category": "工作职场", "target": "领导", "raw": "请领导或同事给工作反馈", "front": "对领导说：请领导或同事给工作反馈"},
    {"id": "work-receive-criticism", "category": "工作职场", "target": "领导", "raw": "接受批评并表达改进态度", "front": "对领导说：接受批评并表达改进态度"},
    {"id": "work-apologize", "category": "工作职场", "target": "领导", "raw": "为工作失误道歉", "front": "对领导说：为工作失误道歉"},
    {"id": "work-ask-policy", "category": "工作职场", "target": "HR", "raw": "询问公司政策或规定", "front": "对HR说：询问公司政策或规定"},
    {"id": "work-networking", "category": "工作职场", "target": "同行", "raw": "行业活动里自我介绍并交换联系方式", "front": "对同行说：行业活动里自我介绍并交换联系方式"},
    {"id": "work-ask-training", "category": "工作职场", "target": "HR", "raw": "询问有没有培训机会", "front": "对HR说：询问有没有培训机会"},
    {"id": "work-ask-promotion", "category": "工作职场", "target": "领导", "raw": "委婉询问晋升机会", "front": "对领导说：委婉询问晋升机会"},
    {"id": "work-leave-early", "category": "工作职场", "target": "领导", "raw": "临时有事想早走", "front": "对领导说：临时有事想早走"},
    {"id": "work-reimbursement", "category": "工作职场", "target": "财务人员", "raw": "问报销流程", "front": "对财务人员说：问报销流程"},
    {"id": "meeting-start", "category": "会议讨论", "target": "与会者", "raw": "主持会议的开场白", "front": "对与会者说：主持会议的开场白"},
    {"id": "meeting-opinion", "category": "会议讨论", "target": "与会者", "raw": "表达自己的看法", "front": "对与会者说：表达自己的看法"},
    {"id": "meeting-agree", "category": "会议讨论", "target": "与会者", "raw": "表达完全同意", "front": "对与会者说：表达完全同意"},
    {"id": "meeting-agree-reservation", "category": "会议讨论", "target": "与会者", "raw": "同意但有保留意见", "front": "对与会者说：同意但有保留意见"},
    {"id": "meeting-disagree", "category": "会议讨论", "target": "与会者", "raw": "礼貌表达不同意", "front": "对与会者说：礼貌表达不同意"},
    {"id": "meeting-ask-opinion", "category": "会议讨论", "target": "与会者", "raw": "询问他人的意见", "front": "对与会者说：询问他人的意见"},
    {"id": "meeting-ask-clarify", "category": "会议讨论", "target": "同事", "raw": "请对方解释没听懂的点", "front": "对同事说：请对方解释没听懂的点"},
    {"id": "meeting-ask-repeat", "category": "会议讨论", "target": "同事", "raw": "请对方重复刚才的观点", "front": "对同事说：请对方重复刚才的观点"},
    {"id": "meeting-summarize", "category": "会议讨论", "target": "与会者", "raw": "总结讨论内容", "front": "对与会者说：总结讨论内容"},
    {"id": "meeting-assign-tasks", "category": "会议讨论", "target": "与会者", "raw": "分工并确认下一步行动", "front": "对与会者说：分工并确认下一步行动"},
    {"id": "meeting-new-topic", "category": "会议讨论", "target": "与会者", "raw": "提出一个新话题", "front": "对与会者说：提出一个新话题"},
    {"id": "meeting-interrupt", "category": "会议讨论", "target": "与会者", "raw": "礼貌打断并补充一句", "front": "对与会者说：礼貌打断并补充一句"},
    {"id": "meeting-offline", "category": "会议讨论", "target": "同事", "raw": "建议细节私下再聊", "front": "对同事说：建议细节私下再聊"},
    {"id": "meeting-close", "category": "会议讨论", "target": "与会者", "raw": "结束会议并确认后续安排", "front": "对与会者说：结束会议并确认后续安排"},
    {"id": "meeting-decision-time", "category": "会议讨论", "target": "与会者", "raw": "问大家什么时候需要做决定", "front": "对与会者说：问大家什么时候需要做决定"},
    {"id": "meeting-request-data", "category": "会议讨论", "target": "同事", "raw": "请同事会后把数据发给我", "front": "对同事说：请同事会后把数据发给我"},
    {"id": "meeting-share-screen", "category": "会议讨论", "target": "与会者", "raw": "请求共享屏幕", "front": "对与会者说：请求共享屏幕"},
    {"id": "meeting-mute", "category": "会议讨论", "target": "与会者", "raw": "请对方静音或打开麦克风（线上会议）", "front": "对与会者说：请对方静音或打开麦克风（线上会议）"},
    {"id": "email-greeting", "category": "邮件与电话", "target": "收件人", "raw": "写正式邮件时的开头称呼与问候", "front": "对收件人说：写正式邮件时的开头称呼与问候"},
    {"id": "email-closing", "category": "邮件与电话", "target": "收件人", "raw": "写正式邮件时的结尾致谢", "front": "对收件人说：写正式邮件时的结尾致谢"},
    {"id": "email-send-file", "category": "邮件与电话", "target": "收件人", "raw": "请求对方发送文件或资料", "front": "对收件人说：请求对方发送文件或资料"},
    {"id": "email-follow-up", "category": "邮件与电话", "target": "收件人", "raw": "追问对方是否收到邮件", "front": "对收件人说：追问对方是否收到邮件"},
    {"id": "email-request-meeting", "category": "邮件与电话", "target": "收件人", "raw": "邮件里约会议时间", "front": "对收件人说：邮件里约会议时间"},
    {"id": "email-apologize-late", "category": "邮件与电话", "target": "收件人", "raw": "邮件里为回复晚了道歉", "front": "对收件人说：邮件里为回复晚了道歉"},
    {"id": "email-attachment", "category": "邮件与电话", "target": "收件人", "raw": "邮件里提醒对方查看附件", "front": "对收件人说：邮件里提醒对方查看附件"},
    {"id": "email-reschedule", "category": "邮件与电话", "target": "收件人", "raw": "邮件里确认改期", "front": "对收件人说：邮件里确认改期"},
    {"id": "email-thanks", "category": "邮件与电话", "target": "收件人", "raw": "收到对方邮件后回复感谢", "front": "对收件人说：收到对方邮件后回复感谢"},
    {"id": "email-forward", "category": "邮件与电话", "target": "收件人", "raw": "请对方转发邮件给同事", "front": "对收件人说：请对方转发邮件给同事"},
    {"id": "email-short", "category": "邮件与电话", "target": "同事", "raw": "写一封简短的非正式邮件（同事之间）", "front": "对同事说：写一封简短的非正式邮件（同事之间）"},
    {"id": "call-open", "category": "邮件与电话", "target": "对方", "raw": "接工作电话时的开场白", "front": "对对方说：接工作电话时的开场白"},
    {"id": "call-ask-person", "category": "邮件与电话", "target": "接电话的人", "raw": "打电话找某个人", "front": "对接电话的人说：打电话找某个人"},
    {"id": "call-wrong-number", "category": "邮件与电话", "target": "对方", "raw": "打错电话后道歉", "front": "对对方说：打错电话后道歉"},
    {"id": "call-voicemail", "category": "邮件与电话", "target": "对方", "raw": "留言请对方回电", "front": "对对方说：留言请对方回电"},
    {"id": "call-bad-connection", "category": "邮件与电话", "target": "对方", "raw": "电话听不清，请对方再说一遍", "front": "对对方说：电话听不清，请对方再说一遍"},
    {"id": "call-hold", "category": "邮件与电话", "target": "对方", "raw": "请对方稍等（接电话时）", "front": "对对方说：请对方稍等（接电话时）"},
    {"id": "call-transfer", "category": "邮件与电话", "target": "对方", "raw": "请对方转接给另一个人", "front": "对对方说：请对方转接给另一个人"},
    {"id": "call-schedule", "category": "邮件与电话", "target": "对方", "raw": "约一个电话沟通时间", "front": "对对方说：约一个电话沟通时间"},
    {"id": "call-callback", "category": "邮件与电话", "target": "对方", "raw": "请对方有空回电话", "front": "对对方说：请对方有空回电话"},
    {"id": "housing-ask-rental", "category": "租房居住", "target": "房东", "raw": "咨询房源信息（租金）", "front": "对房东说：咨询房源信息（租金）"},
    {"id": "housing-ask-deposit", "category": "租房居住", "target": "房东", "raw": "咨询房源押金", "front": "对房东说：咨询房源押金"},
    {"id": "housing-viewing", "category": "租房居住", "target": "房东", "raw": "约看房时间", "front": "对房东说：约看房时间"},
    {"id": "housing-apply", "category": "租房居住", "target": "房东", "raw": "表达想租房并询问流程", "front": "对房东说：表达想租房并询问流程"},
    {"id": "housing-utilities", "category": "租房居住", "target": "房东", "raw": "问房租是否含水电网费", "front": "对房东说：问房租是否含水电网费"},
    {"id": "housing-rent-due", "category": "租房居住", "target": "房东", "raw": "问房租什么时候交", "front": "对房东说：问房租什么时候交"},
    {"id": "housing-lease-term", "category": "租房居住", "target": "房东", "raw": "问租期最短多久", "front": "对房东说：问租期最短多久"},
    {"id": "housing-lease-clauses", "category": "租房居住", "target": "房东", "raw": "签合同前确认条款", "front": "对房东说：签合同前确认条款"},
    {"id": "housing-faucet", "category": "租房居住", "target": "维修工", "raw": "报修水龙头坏了", "front": "对维修工说：报修水龙头坏了"},
    {"id": "housing-heating", "category": "租房居住", "target": "维修工", "raw": "报修暖气不热", "front": "对维修工说：报修暖气不热"},
    {"id": "housing-leak", "category": "租房居住", "target": "维修工", "raw": "报修漏水", "front": "对维修工说：报修漏水"},
    {"id": "housing-neighbor-quiet", "category": "租房居住", "target": "邻居", "raw": "委婉请邻居安静一点", "front": "对邻居说：委婉请邻居安静一点"},
    {"id": "housing-noise-complaint", "category": "租房居住", "target": "物业", "raw": "向房东或物业投诉噪音", "front": "对物业说：向房东或物业投诉噪音"},
    {"id": "housing-renew", "category": "租房居住", "target": "房东", "raw": "问能否续租", "front": "对房东说：问能否续租"},
    {"id": "housing-move-out", "category": "租房居住", "target": "房东", "raw": "通知退租或搬走", "front": "对房东说：通知退租或搬走"},
    {"id": "housing-deposit-refund", "category": "租房居住", "target": "房东", "raw": "问押金什么时候退还", "front": "对房东说：问押金什么时候退还"},
    {"id": "housing-parking", "category": "租房居住", "target": "房东", "raw": "问有没有停车位", "front": "对房东说：问有没有停车位"},
    {"id": "housing-pet-policy", "category": "租房居住", "target": "房东", "raw": "问能不能养宠物", "front": "对房东说：问能不能养宠物"},
    {"id": "housing-internet-available", "category": "租房居住", "target": "房东", "raw": "问房子里有没有网络", "front": "对房东说：问房子里有没有网络"},
    {"id": "housing-internet-setup", "category": "租房居住", "target": "客服", "raw": "问怎么装宽带", "front": "对客服说：问怎么装宽带"},
    {"id": "housing-urgent-repair", "category": "租房居住", "target": "维修工", "raw": "紧急报修（停电）", "front": "对维修工说：紧急报修（停电）"},
    {"id": "shop-ask-price", "category": "购物消费", "target": "店员", "raw": "问价格", "front": "对店员说：问价格"},
    {"id": "shop-try-on", "category": "购物消费", "target": "店员", "raw": "请求试穿", "front": "对店员说：请求试穿"},
    {"id": "shop-try-demo", "category": "购物消费", "target": "店员", "raw": "请求试用或试玩", "front": "对店员说：请求试用或试玩"},
    {"id": "shop-ask-size", "category": "购物消费", "target": "店员", "raw": "问有没有其他尺寸", "front": "对店员说：问有没有其他尺寸"},
    {"id": "shop-ask-color", "category": "购物消费", "target": "店员", "raw": "问有没有其他颜色", "front": "对店员说：问有没有其他颜色"},
    {"id": "shop-bargain", "category": "购物消费", "target": "店主", "raw": "在市场或二手店礼貌砍价", "front": "对店主说：在市场或二手店礼貌砍价"},
    {"id": "shop-discount", "category": "购物消费", "target": "店员", "raw": "问有没有折扣", "front": "对店员说：问有没有折扣"},
    {"id": "shop-student-discount", "category": "购物消费", "target": "店员", "raw": "问有没有学生优惠", "front": "对店员说：问有没有学生优惠"},
    {"id": "shop-pay-separately", "category": "购物消费", "target": "店员", "raw": "要求分开结账", "front": "对店员说：要求分开结账"},
    {"id": "shop-receipt", "category": "购物消费", "target": "店员", "raw": "要收据", "front": "对店员说：要收据"},
    {"id": "shop-invoice", "category": "购物消费", "target": "店员", "raw": "要发票", "front": "对店员说：要发票"},
    {"id": "shop-return", "category": "购物消费", "target": "店员", "raw": "退货", "front": "对店员说：退货"},
    {"id": "shop-exchange", "category": "购物消费", "target": "店员", "raw": "换货", "front": "对店员说：换货"},
    {"id": "shop-refund", "category": "购物消费", "target": "店员", "raw": "要求退款", "front": "对店员说：要求退款"},
    {"id": "shop-warranty", "category": "购物消费", "target": "店员", "raw": "问保修期多久", "front": "对店员说：问保修期多久"},
    {"id": "shop-return-policy", "category": "购物消费", "target": "店员", "raw": "问退换政策", "front": "对店员说：问退换政策"},
    {"id": "shop-delivery-time", "category": "购物消费", "target": "店员", "raw": "问送货时间", "front": "对店员说：问送货时间"},
    {"id": "shop-delivery-fee", "category": "购物消费", "target": "店员", "raw": "问运费", "front": "对店员说：问运费"},
    {"id": "shop-size-guide", "category": "购物消费", "target": "店员", "raw": "网购时问尺码怎么选", "front": "对店员说：网购时问尺码怎么选"},
    {"id": "shop-stock-available", "category": "购物消费", "target": "店员", "raw": "问有没有货", "front": "对店员说：问有没有货"},
    {"id": "shop-restock", "category": "购物消费", "target": "店员", "raw": "问什么时候补货", "front": "对店员说：问什么时候补货"},
    {"id": "shop-bag", "category": "购物消费", "target": "店员", "raw": "要一个购物袋", "front": "对店员说：要一个购物袋"},
    {"id": "shop-membership", "category": "购物消费", "target": "店员", "raw": "问有没有会员积分或优惠卡", "front": "对店员说：问有没有会员积分或优惠卡"},
    {"id": "food-book-table", "category": "餐饮", "target": "服务员", "raw": "订餐厅座位", "front": "对服务员说：订餐厅座位"},
    {"id": "food-recommendation", "category": "餐饮", "target": "服务员", "raw": "请服务员推荐招牌菜", "front": "对服务员说：请服务员推荐招牌菜"},
    {"id": "food-order", "category": "餐饮", "target": "服务员", "raw": "点餐", "front": "对服务员说：点餐"},
    {"id": "food-allergy", "category": "餐饮", "target": "服务员", "raw": "告诉服务员自己对某种食物过敏", "front": "对服务员说：告诉服务员自己对某种食物过敏"},
    {"id": "food-vegetarian", "category": "餐饮", "target": "服务员", "raw": "说明自己是素食者", "front": "对服务员说：说明自己是素食者"},
    {"id": "food-no-spicy", "category": "餐饮", "target": "服务员", "raw": "说明自己不吃辣", "front": "对服务员说：说明自己不吃辣"},
    {"id": "food-less-salt", "category": "餐饮", "target": "服务员", "raw": "要求菜少放盐", "front": "对服务员说：要求菜少放盐"},
    {"id": "food-less-sugar", "category": "餐饮", "target": "服务员", "raw": "要求菜少放糖", "front": "对服务员说：要求菜少放糖"},
    {"id": "food-no-ice", "category": "餐饮", "target": "服务员", "raw": "饮料不加冰", "front": "对服务员说：饮料不加冰"},
    {"id": "food-ice-free", "category": "餐饮", "target": "服务员", "raw": "饮料去冰", "front": "对服务员说：饮料去冰"},
    {"id": "food-little-ice", "category": "餐饮", "target": "服务员", "raw": "饮料少冰", "front": "对服务员说：饮料少冰"},
    {"id": "food-normal-ice", "category": "餐饮", "target": "服务员", "raw": "饮料正常冰", "front": "对服务员说：饮料正常冰"},
    {"id": "food-check-order", "category": "餐饮", "target": "服务员", "raw": "催单或确认菜还没上", "front": "对服务员说：催单或确认菜还没上"},
    {"id": "food-delicious", "category": "餐饮", "target": "服务员", "raw": "夸菜好吃", "front": "对服务员说：夸菜好吃"},
    {"id": "food-too-salty", "category": "餐饮", "target": "服务员", "raw": "菜太咸，请处理", "front": "对服务员说：菜太咸，请处理"},
    {"id": "food-not-fresh", "category": "餐饮", "target": "服务员", "raw": "菜不新鲜，请处理", "front": "对服务员说：菜不新鲜，请处理"},
    {"id": "food-bill", "category": "餐饮", "target": "服务员", "raw": "买单", "front": "对服务员说：买单"},
    {"id": "food-split-bill", "category": "餐饮", "target": "服务员", "raw": "AA 结账", "front": "对服务员说：AA 结账"},
    {"id": "food-tip", "category": "餐饮", "target": "服务员", "raw": "问是否需要小费", "front": "对服务员说：问是否需要小费"},
    {"id": "food-takeaway", "category": "餐饮", "target": "服务员", "raw": "要求打包", "front": "对服务员说：要求打包"},
    {"id": "food-water", "category": "餐饮", "target": "服务员", "raw": "请服务员加水", "front": "对服务员说：请服务员加水"},
    {"id": "food-refill", "category": "餐饮", "target": "服务员", "raw": "饮料续杯", "front": "对服务员说：饮料续杯"},
    {"id": "food-napkin", "category": "餐饮", "target": "服务员", "raw": "多要一份餐巾纸", "front": "对服务员说：多要一份餐巾纸"},
    {"id": "food-spicy-level", "category": "餐饮", "target": "服务员", "raw": "问这道菜辣不辣", "front": "对服务员说：问这道菜辣不辣"},
    {"id": "food-steak", "category": "餐饮", "target": "服务员", "raw": "牛排要几分熟", "front": "对服务员说：牛排要几分熟"},
    {"id": "food-wait-time", "category": "餐饮", "target": "服务员", "raw": "问菜还要等多久", "front": "对服务员说：问菜还要等多久"},
    {"id": "travel-ask-route", "category": "交通出行", "target": "路人", "raw": "问怎么去某个地方", "front": "对路人说：问怎么去某个地方"},
    {"id": "travel-buy-ticket", "category": "交通出行", "target": "售票员", "raw": "买车票", "front": "对售票员说：买车票"},
    {"id": "travel-buy-metro", "category": "交通出行", "target": "售票员", "raw": "买地铁票", "front": "对售票员说：买地铁票"},
    {"id": "travel-departure", "category": "交通出行", "target": "工作人员", "raw": "问发车时间", "front": "对工作人员说：问发车时间"},
    {"id": "travel-arrival", "category": "交通出行", "target": "工作人员", "raw": "问到站时间", "front": "对工作人员说：问到站时间"},
    {"id": "travel-missed-bus", "category": "交通出行", "target": "工作人员", "raw": "错过车了，问接下来怎么办", "front": "对工作人员说：错过车了，问接下来怎么办"},
    {"id": "travel-taxi-destination", "category": "交通出行", "target": "出租车司机", "raw": "告诉司机目的地", "front": "对出租车司机说：告诉司机目的地"},
    {"id": "travel-taxi-fare", "category": "交通出行", "target": "出租车司机", "raw": "问车费大概多少", "front": "对出租车司机说：问车费大概多少"},
    {"id": "travel-bus-stop", "category": "交通出行", "target": "司机", "raw": "问哪一站下车", "front": "对司机说：问哪一站下车"},
    {"id": "travel-transfer", "category": "交通出行", "target": "工作人员", "raw": "问要不要换乘", "front": "对工作人员说：问要不要换乘"},
    {"id": "travel-rent-car", "category": "交通出行", "target": "租车公司员工", "raw": "租车（保险）", "front": "对租车公司员工说：租车（保险）"},
    {"id": "travel-return-car", "category": "交通出行", "target": "租车公司员工", "raw": "租车还车流程", "front": "对租车公司员工说：租车还车流程"},
    {"id": "travel-ride-share", "category": "交通出行", "target": "网约车司机", "raw": "叫车后和司机确认路线", "front": "对网约车司机说：叫车后和司机确认路线"},
    {"id": "travel-traffic", "category": "交通出行", "target": "朋友", "raw": "抱怨堵车或问路况", "front": "对朋友说：抱怨堵车或问路况"},
    {"id": "travel-lost-taxi", "category": "交通出行", "target": "出租车公司客服", "raw": "东西落在出租车上了", "front": "对出租车公司客服说：东西落在出租车上了"},
    {"id": "travel-lost-metro", "category": "交通出行", "target": "地铁工作人员", "raw": "东西落在地铁上了", "front": "对地铁工作人员说：东西落在地铁上了"},
    {"id": "travel-bike-share", "category": "交通出行", "target": "工作人员", "raw": "问共享单车怎么借还", "front": "对工作人员说：问共享单车怎么借还"},
    {"id": "travel-parking-spot", "category": "交通出行", "target": "工作人员", "raw": "找停车位", "front": "对工作人员说：找停车位"},
    {"id": "travel-parking-fee", "category": "交通出行", "target": "工作人员", "raw": "问停车费", "front": "对工作人员说：问停车费"},
    {"id": "travel-bus-frequency", "category": "交通出行", "target": "工作人员", "raw": "问公交多久一班", "front": "对工作人员说：问公交多久一班"},
    {"id": "direction-ask", "category": "问路与方向", "target": "路人", "raw": "礼貌地问路", "front": "对路人说：礼貌地问路"},
    {"id": "direction-confirm", "category": "问路与方向", "target": "路人", "raw": "确认自己走的方向对不对", "front": "对路人说：确认自己走的方向对不对"},
    {"id": "direction-distance", "category": "问路与方向", "target": "路人", "raw": "问距离远不远", "front": "对路人说：问距离远不远"},
    {"id": "direction-landmark", "category": "问路与方向", "target": "路人", "raw": "问附近有什么地标", "front": "对路人说：问附近有什么地标"},
    {"id": "direction-cant-find", "category": "问路与方向", "target": "朋友", "raw": "找不到地方，电话求助", "front": "对朋友说：找不到地方，电话求助"},
    {"id": "direction-entrance", "category": "问路与方向", "target": "路人", "raw": "问入口在哪", "front": "对路人说：问入口在哪"},
    {"id": "direction-floor", "category": "问路与方向", "target": "路人", "raw": "问在第几层或哪个楼层", "front": "对路人说：问在第几层或哪个楼层"},
    {"id": "direction-lost", "category": "问路与方向", "target": "路人", "raw": "迷路了，向路人求助", "front": "对路人说：迷路了，向路人求助"},
    {"id": "direction-walk-time", "category": "问路与方向", "target": "路人", "raw": "问步行大概多久", "front": "对路人说：问步行大概多久"},
    {"id": "direction-drive-time", "category": "问路与方向", "target": "路人", "raw": "问开车大概多久", "front": "对路人说：问开车大概多久"},
    {"id": "direction-nearest-station", "category": "问路与方向", "target": "路人", "raw": "问最近的地铁站或公交站", "front": "对路人说：问最近的地铁站或公交站"},
    {"id": "direction-turn", "category": "问路与方向", "target": "路人", "raw": "问该往左还是往右", "front": "对路人说：问该往左还是往右"},
    {"id": "direction-safety", "category": "问路与方向", "target": "路人", "raw": "问这条路晚上安不安全", "front": "对路人说：问这条路晚上安不安全"},
    {"id": "direction-shortcut", "category": "问路与方向", "target": "路人", "raw": "问有没有近路", "front": "对路人说：问有没有近路"},
    {"id": "bank-open-account", "category": "银行与办事", "target": "银行柜员", "raw": "开银行账户", "front": "对银行柜员说：开银行账户"},
    {"id": "bank-account-fee", "category": "银行与办事", "target": "银行柜员", "raw": "问账户有没有月费", "front": "对银行柜员说：问账户有没有月费"},
    {"id": "bank-transfer-fee", "category": "银行与办事", "target": "银行柜员", "raw": "问转账手续费", "front": "对银行柜员说：问转账手续费"},
    {"id": "bank-withdraw", "category": "银行与办事", "target": "银行柜员", "raw": "取钱", "front": "对银行柜员说：取钱"},
    {"id": "bank-deposit", "category": "银行与办事", "target": "银行柜员", "raw": "存钱", "front": "对银行柜员说：存钱"},
    {"id": "bank-transfer", "category": "银行与办事", "target": "银行柜员", "raw": "转账", "front": "对银行柜员说：转账"},
    {"id": "bank-card-lost", "category": "银行与办事", "target": "银行客服", "raw": "银行卡丢了要挂失", "front": "对银行客服说：银行卡丢了要挂失"},
    {"id": "bank-exchange", "category": "银行与办事", "target": "银行柜员", "raw": "换外汇", "front": "对银行柜员说：换外汇"},
    {"id": "bank-exchange-rate", "category": "银行与办事", "target": "银行柜员", "raw": "问汇率", "front": "对银行柜员说：问汇率"},
    {"id": "bank-mail-package", "category": "银行与办事", "target": "邮局工作人员", "raw": "寄包裹并问邮费", "front": "对邮局工作人员说：寄包裹并问邮费"},
    {"id": "bank-mail-overseas", "category": "银行与办事", "target": "邮局工作人员", "raw": "寄国际包裹", "front": "对邮局工作人员说：寄国际包裹"},
    {"id": "bank-collect-package", "category": "银行与办事", "target": "邮局工作人员", "raw": "取包裹并问需要什么证件", "front": "对邮局工作人员说：取包裹并问需要什么证件"},
    {"id": "bank-register-doc", "category": "银行与办事", "target": "工作人员", "raw": "咨询证件或注册办理", "front": "对工作人员说：咨询证件或注册办理"},
    {"id": "bank-appointment", "category": "银行与办事", "target": "工作人员", "raw": "预约办事时间（签证或市政厅）", "front": "对工作人员说：预约办事时间（签证或市政厅）"},
    {"id": "bank-ask-form", "category": "银行与办事", "target": "工作人员", "raw": "问表格怎么填", "front": "对工作人员说：问表格怎么填"},
    {"id": "bank-insurance-claim", "category": "银行与办事", "target": "保险公司客服", "raw": "咨询保险理赔", "front": "对保险公司客服说：咨询保险理赔"},
    {"id": "bank-police-report", "category": "银行与办事", "target": "警察", "raw": "报案", "front": "对警察说：报案"},
    {"id": "bank-certificate", "category": "银行与办事", "target": "工作人员", "raw": "问怎么开证明", "front": "对工作人员说：问怎么开证明"},
    {"id": "bank-office-hours", "category": "银行与办事", "target": "工作人员", "raw": "问办事窗口营业时间", "front": "对工作人员说：问办事窗口营业时间"},
    {"id": "bank-notary", "category": "银行与办事", "target": "公证处工作人员", "raw": "问公证怎么办理", "front": "对公证处工作人员说：问公证怎么办理"},
    {"id": "health-book-doctor", "category": "医疗健康", "target": "前台", "raw": "预约看医生", "front": "对前台说：预约看医生"},
    {"id": "health-headache", "category": "医疗健康", "target": "医生", "raw": "描述头疼", "front": "对医生说：描述头疼"},
    {"id": "health-fever", "category": "医疗健康", "target": "医生", "raw": "描述发烧", "front": "对医生说：描述发烧"},
    {"id": "health-cough", "category": "医疗健康", "target": "医生", "raw": "描述咳嗽", "front": "对医生说：描述咳嗽"},
    {"id": "health-stomach", "category": "医疗健康", "target": "医生", "raw": "描述胃疼", "front": "对医生说：描述胃疼"},
    {"id": "health-injury", "category": "医疗健康", "target": "医生", "raw": "描述扭伤或受伤", "front": "对医生说：描述扭伤或受伤"},
    {"id": "health-medicine", "category": "医疗健康", "target": "医生", "raw": "问药怎么吃", "front": "对医生说：问药怎么吃"},
    {"id": "health-dose", "category": "医疗健康", "target": "医生", "raw": "问一次吃几粒", "front": "对医生说：问一次吃几粒"},
    {"id": "health-side-effects", "category": "医疗健康", "target": "医生", "raw": "问药有没有副作用", "front": "对医生说：问药有没有副作用"},
    {"id": "health-pharmacy", "category": "医疗健康", "target": "药剂师", "raw": "在药店买非处方药", "front": "对药剂师说：在药店买非处方药"},
    {"id": "health-allergy", "category": "医疗健康", "target": "医生", "raw": "告诉医生自己过敏", "front": "对医生说：告诉医生自己过敏"},
    {"id": "health-emergency", "category": "医疗健康", "target": "路人", "raw": "突然不舒服，向人求助", "front": "对路人说：突然不舒服，向人求助"},
    {"id": "health-referral", "category": "医疗健康", "target": "医生", "raw": "问要不要转专科", "front": "对医生说：问要不要转专科"},
    {"id": "health-result", "category": "医疗健康", "target": "医生", "raw": "问检查结果", "front": "对医生说：问检查结果"},
    {"id": "health-sick-leave", "category": "医疗健康", "target": "老师或领导", "raw": "向学校或公司请病假", "front": "对老师或领导说：向学校或公司请病假"},
    {"id": "health-dentist", "category": "医疗健康", "target": "医生", "raw": "牙疼，约牙医", "front": "对医生说：牙疼，约牙医"},
    {"id": "health-insurance", "category": "医疗健康", "target": "医生", "raw": "问保险是否覆盖这项医疗", "front": "对医生说：问保险是否覆盖这项医疗"},
    {"id": "health-counseling", "category": "医疗健康", "target": "心理咨询师", "raw": "压力大，想找心理咨询", "front": "对心理咨询师说：压力大，想找心理咨询"},
    {"id": "health-wait", "category": "医疗健康", "target": "前台", "raw": "问看病还要等多久", "front": "对前台说：问看病还要等多久"},
    {"id": "health-direction", "category": "医疗健康", "target": "工作人员", "raw": "问化验室或药房在哪", "front": "对工作人员说：问化验室或药房在哪"},
    {"id": "health-vaccine", "category": "医疗健康", "target": "护士", "raw": "问流感疫苗怎么打", "front": "对护士说：问流感疫苗怎么打"},
    {"id": "health-prescription", "category": "医疗健康", "target": "医生", "raw": "问怎么续开处方药", "front": "对医生说：问怎么续开处方药"},
    {"id": "social-invite-casual", "category": "社交邀约", "target": "朋友", "raw": "约朋友周末一起玩", "front": "对朋友说：约朋友周末一起玩"},
    {"id": "social-invite-formal", "category": "社交邀约", "target": "同事", "raw": "邀请同事或同学参加活动", "front": "对同事说：邀请同事或同学参加活动"},
    {"id": "social-accept", "category": "社交邀约", "target": "朋友", "raw": "接受邀请并确认时间", "front": "对朋友说：接受邀请并确认时间"},
    {"id": "social-decline-invitation", "category": "社交邀约", "target": "朋友", "raw": "婉拒邀请（不想去又不扫兴）", "front": "对朋友说：婉拒邀请（不想去又不扫兴）"},
    {"id": "social-ask-availability", "category": "社交邀约", "target": "朋友", "raw": "问对方什么时候有空", "front": "对朋友说：问对方什么时候有空"},
    {"id": "social-suggest-time", "category": "社交邀约", "target": "朋友", "raw": "提议一个具体时间", "front": "对朋友说：提议一个具体时间"},
    {"id": "social-change-plan", "category": "社交邀约", "target": "朋友", "raw": "计划有变，改时间并道歉", "front": "对朋友说：计划有变，改时间并道歉"},
    {"id": "social-ask-bring", "category": "社交邀约", "target": "朋友", "raw": "问聚会要不要带点东西", "front": "对朋友说：问聚会要不要带点东西"},
    {"id": "social-host", "category": "社交邀约", "target": "客人", "raw": "招待客人（请进或喝点什么）", "front": "对客人说：招待客人（请进或喝点什么）"},
    {"id": "social-late", "category": "社交邀约", "target": "朋友", "raw": "迟到道歉并说明情况", "front": "对朋友说：迟到道歉并说明情况"},
    {"id": "social-thank-host", "category": "社交邀约", "target": "主人", "raw": "离开时感谢主人招待", "front": "对主人说：离开时感谢主人招待"},
    {"id": "social-follow-up", "category": "社交邀约", "target": "朋友", "raw": "聚会后说玩得很开心", "front": "对朋友说：聚会后说玩得很开心"},
    {"id": "social-ask-recipe", "category": "社交邀约", "target": "朋友", "raw": "问对方要一道菜的食谱", "front": "对朋友说：问对方要一道菜的食谱"},
    {"id": "social-ask-photo", "category": "社交邀约", "target": "朋友", "raw": "问能不能把照片发给我", "front": "对朋友说：问能不能把照片发给我"},
    {"id": "social-borrow", "category": "社交邀约", "target": "朋友", "raw": "向朋友借东西", "front": "对朋友说：向朋友借东西"},
    {"id": "social-return", "category": "社交邀约", "target": "朋友", "raw": "还朋友东西并道谢", "front": "对朋友说：还朋友东西并道谢"},
    {"id": "social-plan-trip", "category": "社交邀约", "target": "朋友", "raw": "约朋友一起计划旅行", "front": "对朋友说：约朋友一起计划旅行"},
    {"id": "social-ask-gift", "category": "社交邀约", "target": "朋友", "raw": "问朋友生日想要什么礼物", "front": "对朋友说：问朋友生日想要什么礼物"},
    {"id": "emotion-ask-help", "category": "情绪与求助", "target": "陌生人", "raw": "向陌生人礼貌求助", "front": "对陌生人说：向陌生人礼貌求助"},
    {"id": "emotion-ask-explain", "category": "情绪与求助", "target": "对方", "raw": "没听懂，请对方再解释一遍", "front": "对对方说：没听懂，请对方再解释一遍"},
    {"id": "emotion-ask-slowly", "category": "情绪与求助", "target": "对方", "raw": "请对方说慢一点", "front": "对对方说：请对方说慢一点"},
    {"id": "emotion-confused", "category": "情绪与求助", "target": "对方", "raw": "表示自己没跟上", "front": "对对方说：表示自己没跟上"},
    {"id": "emotion-write-down", "category": "情绪与求助", "target": "对方", "raw": "请对方把关键信息写下来", "front": "对对方说：请对方把关键信息写下来"},
    {"id": "emotion-stress", "category": "情绪与求助", "target": "朋友", "raw": "表达压力大或很累", "front": "对朋友说：表达压力大或很累"},
    {"id": "emotion-uncertain", "category": "情绪与求助", "target": "对方", "raw": "表达不确定，需要时间想想", "front": "对对方说：表达不确定，需要时间想想"},
    {"id": "emotion-recommendation", "category": "情绪与求助", "target": "当地人", "raw": "请当地人推荐好地方", "front": "对当地人说：请当地人推荐好地方"},
    {"id": "emotion-need-someone", "category": "情绪与求助", "target": "朋友", "raw": "情绪低落，想找人说说话", "front": "对朋友说：情绪低落，想找人说说话"},
    {"id": "emotion-translate", "category": "情绪与求助", "target": "路人", "raw": "请人帮忙翻译或转告", "front": "对路人说：请人帮忙翻译或转告"},
    {"id": "emotion-apologize", "category": "情绪与求助", "target": "对方", "raw": "为自己的错误道歉", "front": "对对方说：为自己的错误道歉"},
    {"id": "emotion-pardon", "category": "情绪与求助", "target": "对方", "raw": "没听清，请对方重复（口语）", "front": "对对方说：没听清，请对方重复（口语）"},
    {"id": "emotion-worry", "category": "情绪与求助", "target": "朋友", "raw": "表达担心", "front": "对朋友说：表达担心"},
    {"id": "emotion-disappointed", "category": "情绪与求助", "target": "朋友", "raw": "表达失望", "front": "对朋友说：表达失望"},
    {"id": "emotion-advice", "category": "情绪与求助", "target": "朋友", "raw": "请对方给建议", "front": "对朋友说：请对方给建议"},
    {"id": "emotion-no", "category": "情绪与求助", "target": "对方", "raw": "需要直接说不（不解释太多）", "front": "对对方说：需要直接说不（不解释太多）"},
    {"id": "emotion-deep-thanks", "category": "情绪与求助", "target": "对方", "raw": "表达特别感激", "front": "对对方说：表达特别感激"},
    {"id": "emotion-calm", "category": "情绪与求助", "target": "对方", "raw": "请对方冷静（冲突时）", "front": "对对方说：请对方冷静（冲突时）"},
    {"id": "emergency-police", "category": "突发状况", "target": "警察", "raw": "报警", "front": "对警察说：报警"},
    {"id": "emergency-ambulance", "category": "突发状况", "target": "急救人员", "raw": "叫急救", "front": "对急救人员说：叫急救"},
    {"id": "emergency-fire", "category": "突发状况", "target": "消防员", "raw": "着火了，求助", "front": "对消防员说：着火了，求助"},
    {"id": "emergency-accident", "category": "突发状况", "target": "警察", "raw": "发生车祸，需要处理", "front": "对警察说：发生车祸，需要处理"},
    {"id": "emergency-passport", "category": "突发状况", "target": "警察", "raw": "护照丢了", "front": "对警察说：护照丢了"},
    {"id": "emergency-wallet", "category": "突发状况", "target": "警察", "raw": "钱包被偷", "front": "对警察说：钱包被偷"},
    {"id": "emergency-child-lost", "category": "突发状况", "target": "警察", "raw": "孩子走失了", "front": "对警察说：孩子走失了"},
    {"id": "emergency-companion-lost", "category": "突发状况", "target": "警察", "raw": "同伴走失了", "front": "对警察说：同伴走失了"},
    {"id": "emergency-power", "category": "突发状况", "target": "物业", "raw": "停电了，询问情况", "front": "对物业说：停电了，询问情况"},
    {"id": "emergency-collapse", "category": "突发状况", "target": "急救人员", "raw": "有人晕倒或受伤，呼救", "front": "对急救人员说：有人晕倒或受伤，呼救"},
    {"id": "emergency-locked-out", "category": "突发状况", "target": "维修工", "raw": "门锁坏了进不去", "front": "对维修工说：门锁坏了进不去"},
    {"id": "emergency-phone-lost", "category": "突发状况", "target": "警察", "raw": "手机丢了", "front": "对警察说：手机丢了"},
    {"id": "emergency-safe-area", "category": "突发状况", "target": "工作人员", "raw": "问避难地点", "front": "对工作人员说：问避难地点"},
    {"id": "emergency-earthquake", "category": "突发状况", "target": "工作人员", "raw": "地震了，问怎么避险", "front": "对工作人员说：地震了，问怎么避险"},
    {"id": "emergency-gas-leak", "category": "突发状况", "target": "燃气公司客服", "raw": "闻到燃气味", "front": "对燃气公司客服说：闻到燃气味"},
    {"id": "emergency-burglary", "category": "突发状况", "target": "警察", "raw": "家里进贼了", "front": "对警察说：家里进贼了"},
    {"id": "goodbye-casual", "category": "告别与结束", "target": "朋友", "raw": "和朋友简单告别", "front": "对朋友说：和朋友简单告别"},
    {"id": "goodbye-formal", "category": "告别与结束", "target": "同事", "raw": "和同事或客户正式告别", "front": "对同事说：和同事或客户正式告别"},
    {"id": "goodbye-see-you", "category": "告别与结束", "target": "朋友", "raw": "说“回头见或晚点见”", "front": "对朋友说：说“回头见或晚点见”"},
    {"id": "goodbye-leave", "category": "告别与结束", "target": "朋友", "raw": "有事要先走，礼貌离开", "front": "对朋友说：有事要先走，礼貌离开"},
    {"id": "goodbye-phone", "category": "告别与结束", "target": "朋友", "raw": "结束电话", "front": "对朋友说：结束电话"},
    {"id": "goodbye-meeting", "category": "告别与结束", "target": "朋友", "raw": "结束线上会议", "front": "对朋友说：结束线上会议"},
    {"id": "goodbye-wish", "category": "告别与结束", "target": "对方", "raw": "祝对方有美好的一天", "front": "对对方说：祝对方有美好的一天"},
    {"id": "goodbye-travel", "category": "告别与结束", "target": "对方", "raw": "送行时祝一路平安", "front": "对对方说：送行时祝一路平安"},
    {"id": "goodbye-night", "category": "告别与结束", "target": "朋友", "raw": "道晚安", "front": "对朋友说：道晚安"},
    {"id": "goodbye-chat", "category": "告别与结束", "target": "朋友", "raw": "结束闲聊去忙正事", "front": "对朋友说：结束闲聊去忙正事"},
    {"id": "goodbye-email", "category": "告别与结束", "target": "收件人", "raw": "邮件结尾告别", "front": "对收件人说：邮件结尾告别"},
    {"id": "goodbye-tomorrow", "category": "告别与结束", "target": "朋友", "raw": "说“明天见”", "front": "对朋友说：说“明天见”"},
    {"id": "goodbye-thanks", "category": "告别与结束", "target": "对方", "raw": "告别时再次感谢对方", "front": "对对方说：告别时再次感谢对方"},
    {"id": "goodbye-wave", "category": "告别与结束", "target": "对方", "raw": "回应对方的送别", "front": "对对方说：回应对方的送别"},
    {"id": "phone-signal", "category": "手机与网络", "target": "客服", "raw": "信号不好，向对方说明", "front": "对客服说：信号不好，向对方说明"},
    {"id": "phone-wifi-password", "category": "手机与网络", "target": "店主", "raw": "问 WiFi 密码", "front": "对店主说：问 WiFi 密码"},
    {"id": "phone-wifi-slow", "category": "手机与网络", "target": "客服", "raw": "网太慢，问怎么办", "front": "对客服说：网太慢，问怎么办"},
    {"id": "phone-roaming", "category": "手机与网络", "target": "客服", "raw": "问手机漫游怎么开", "front": "对客服说：问手机漫游怎么开"},
    {"id": "phone-top-up", "category": "手机与网络", "target": "客服", "raw": "手机充值", "front": "对客服说：手机充值"},
    {"id": "phone-sim", "category": "手机与网络", "target": "客服", "raw": "买电话卡", "front": "对客服说：买电话卡"},
    {"id": "phone-app", "category": "手机与网络", "target": "朋友", "raw": "问怎么下载某个应用", "front": "对朋友说：问怎么下载某个应用"},
    {"id": "phone-charger", "category": "手机与网络", "target": "朋友", "raw": "手机没电，借充电器", "front": "对朋友说：手机没电，借充电器"},
    {"id": "phone-repair", "category": "手机与网络", "target": "客服", "raw": "手机坏了，找维修", "front": "对客服说：手机坏了，找维修"},
    {"id": "phone-reset-password", "category": "手机与网络", "target": "客服", "raw": "忘记密码，找回", "front": "对客服说：忘记密码，找回"},
    {"id": "phone-verification", "category": "手机与网络", "target": "客服", "raw": "收不到验证码", "front": "对客服说：收不到验证码"},
    {"id": "phone-video-call", "category": "手机与网络", "target": "朋友", "raw": "约视频通话", "front": "对朋友说：约视频通话"},
    {"id": "phone-install-software", "category": "手机与网络", "target": "朋友", "raw": "请人帮忙装软件", "front": "对朋友说：请人帮忙装软件"},
    {"id": "phone-print", "category": "手机与网络", "target": "打印店店员", "raw": "打印文件（打印店或图书馆）", "front": "对打印店店员说：打印文件（打印店或图书馆）"},
    {"id": "phone-scan", "category": "手机与网络", "target": "打印店店员", "raw": "扫描文件", "front": "对打印店店员说：扫描文件"},
    {"id": "phone-usb", "category": "手机与网络", "target": "客服", "raw": "用 U 盘拷文件", "front": "对客服说：用 U 盘拷文件"},
    {"id": "phone-login", "category": "手机与网络", "target": "客服", "raw": "登录不上账户", "front": "对客服说：登录不上账户"},
    {"id": "phone-language", "category": "手机与网络", "target": "客服", "raw": "网页是英文，想换中文", "front": "对客服说：网页是英文，想换中文"},
    {"id": "parcel-track", "category": "快递与物流", "target": "客服", "raw": "查快递到哪了", "front": "对客服说：查快递到哪了"},
    {"id": "parcel-delivery-time", "category": "快递与物流", "target": "客服", "raw": "问快递什么时候送到", "front": "对客服说：问快递什么时候送到"},
    {"id": "parcel-missed", "category": "快递与物流", "target": "快递员", "raw": "错过快递，问怎么重新派送", "front": "对快递员说：错过快递，问怎么重新派送"},
    {"id": "parcel-redirect", "category": "快递与物流", "target": "客服", "raw": "改快递收货地址", "front": "对客服说：改快递收货地址"},
    {"id": "parcel-leave", "category": "快递与物流", "target": "快递员", "raw": "请快递员把包裹放门口或驿站", "front": "对快递员说：请快递员把包裹放门口或驿站"},
    {"id": "parcel-return", "category": "快递与物流", "target": "客服", "raw": "退货怎么寄", "front": "对客服说：退货怎么寄"},
    {"id": "parcel-fragile", "category": "快递与物流", "target": "快递员", "raw": "寄易碎品注意事项", "front": "对快递员说：寄易碎品注意事项"},
    {"id": "parcel-weight", "category": "快递与物流", "target": "快递员", "raw": "问包裹多重", "front": "对快递员说：问包裹多重"},
    {"id": "parcel-cost", "category": "快递与物流", "target": "快递员", "raw": "问快递费用", "front": "对快递员说：问快递费用"},
    {"id": "parcel-pickup", "category": "快递与物流", "target": "快递员", "raw": "预约上门取件", "front": "对快递员说：预约上门取件"},
    {"id": "parcel-customs", "category": "快递与物流", "target": "客服", "raw": "包裹被海关扣了", "front": "对客服说：包裹被海关扣了"},
    {"id": "parcel-signature", "category": "快递与物流", "target": "快递员", "raw": "问要不要当面签收", "front": "对快递员说：问要不要当面签收"},
    {"id": "parcel-office", "category": "快递与物流", "target": "快递员", "raw": "把快递送到办公室", "front": "对快递员说：把快递送到办公室"},
    {"id": "parcel-damaged", "category": "快递与物流", "target": "客服", "raw": "收到的包裹破损", "front": "对客服说：收到的包裹破损"},
    {"id": "interview-application", "category": "面试与求职", "target": "HR", "raw": "问申请进度", "front": "对HR说：问申请进度"},
    {"id": "interview-intro", "category": "面试与求职", "target": "面试官", "raw": "面试自我介绍", "front": "对面试官说：面试自我介绍"},
    {"id": "interview-duty", "category": "面试与求职", "target": "面试官", "raw": "问岗位具体职责", "front": "对面试官说：问岗位具体职责"},
    {"id": "interview-team", "category": "面试与求职", "target": "面试官", "raw": "问团队情况", "front": "对面试官说：问团队情况"},
    {"id": "interview-company", "category": "面试与求职", "target": "面试官", "raw": "问公司文化", "front": "对面试官说：问公司文化"},
    {"id": "interview-hybrid", "category": "面试与求职", "target": "面试官", "raw": "问能不能远程或混合办公", "front": "对面试官说：问能不能远程或混合办公"},
    {"id": "interview-hours", "category": "面试与求职", "target": "面试官", "raw": "问工作时间", "front": "对面试官说：问工作时间"},
    {"id": "interview-vacation", "category": "面试与求职", "target": "面试官", "raw": "问年假怎么算", "front": "对面试官说：问年假怎么算"},
    {"id": "interview-onboarding", "category": "面试与求职", "target": "HR", "raw": "问入职流程", "front": "对HR说：问入职流程"},
    {"id": "interview-accept", "category": "面试与求职", "target": "HR", "raw": "接受录用通知", "front": "对HR说：接受录用通知"},
    {"id": "interview-decline", "category": "面试与求职", "target": "HR", "raw": "婉拒录用通知", "front": "对HR说：婉拒录用通知"},
    {"id": "interview-salary", "category": "面试与求职", "target": "HR", "raw": "谈薪资", "front": "对HR说：谈薪资"},
    {"id": "interview-contract", "category": "面试与求职", "target": "HR", "raw": "问合同细节", "front": "对HR说：问合同细节"},
    {"id": "interview-reference", "category": "面试与求职", "target": "推荐人", "raw": "问能不能找对方做推荐人", "front": "对推荐人说：问能不能找对方做推荐人"},
    {"id": "interview-thank", "category": "面试与求职", "target": "面试官", "raw": "面试后写感谢邮件", "front": "对面试官说：面试后写感谢邮件"},
    {"id": "interview-deadline", "category": "面试与求职", "target": "HR", "raw": "问什么时候出结果", "front": "对HR说：问什么时候出结果"},
    {"id": "interview-gap", "category": "面试与求职", "target": "面试官", "raw": "解释简历空窗期", "front": "对面试官说：解释简历空窗期"},
    {"id": "interview-internship", "category": "面试与求职", "target": "HR", "raw": "问实习机会", "front": "对HR说：问实习机会"},
    {"id": "airport-checkin", "category": "机场与出入境", "target": "地勤人员", "raw": "办理值机", "front": "对地勤人员说：办理值机"},
    {"id": "airport-luggage", "category": "机场与出入境", "target": "地勤人员", "raw": "托运行李", "front": "对地勤人员说：托运行李"},
    {"id": "airport-carry-on", "category": "机场与出入境", "target": "地勤人员", "raw": "问随身行李限额", "front": "对地勤人员说：问随身行李限额"},
    {"id": "airport-gate", "category": "机场与出入境", "target": "地勤人员", "raw": "问登机口在哪", "front": "对地勤人员说：问登机口在哪"},
    {"id": "airport-delay", "category": "机场与出入境", "target": "航空公司客服", "raw": "问航班晚点情况", "front": "对航空公司客服说：问航班晚点情况"},
    {"id": "airport-cancel", "category": "机场与出入境", "target": "航空公司客服", "raw": "航班取消了怎么办", "front": "对航空公司客服说：航班取消了怎么办"},
    {"id": "airport-boarding", "category": "机场与出入境", "target": "地勤人员", "raw": "登机", "front": "对地勤人员说：登机"},
    {"id": "airport-customs", "category": "机场与出入境", "target": "海关人员", "raw": "海关申报", "front": "对海关人员说：海关申报"},
    {"id": "airport-passport", "category": "机场与出入境", "target": "边检人员", "raw": "过边检", "front": "对边检人员说：过边检"},
    {"id": "airport-visa", "category": "机场与出入境", "target": "移民局工作人员", "raw": "问签证有效期", "front": "对移民局工作人员说：问签证有效期"},
    {"id": "airport-transit", "category": "机场与出入境", "target": "地勤人员", "raw": "转机怎么走", "front": "对地勤人员说：转机怎么走"},
    {"id": "airport-lost-luggage", "category": "机场与出入境", "target": "行李查询处工作人员", "raw": "行李丢了", "front": "对行李查询处工作人员说：行李丢了"},
    {"id": "airport-seat", "category": "机场与出入境", "target": "空乘", "raw": "想换座位", "front": "对空乘说：想换座位"},
    {"id": "airport-meal", "category": "机场与出入境", "target": "空乘", "raw": "订特殊餐（素食等）", "front": "对空乘说：订特殊餐（素食等）"},
    {"id": "airport-form", "category": "机场与出入境", "target": "边检人员", "raw": "入境卡怎么填", "front": "对边检人员说：入境卡怎么填"},
    {"id": "airport-connection", "category": "机场与出入境", "target": "地勤人员", "raw": "问转机时间够不够", "front": "对地勤人员说：问转机时间够不够"},
    {"id": "fun-movie-ticket", "category": "娱乐与休闲", "target": "工作人员", "raw": "买电影票", "front": "对工作人员说：买电影票"},
    {"id": "fun-movie", "category": "娱乐与休闲", "target": "朋友", "raw": "问最近有什么好看的电影", "front": "对朋友说：问最近有什么好看的电影"},
    {"id": "fun-concert", "category": "娱乐与休闲", "target": "朋友", "raw": "问演唱会门票", "front": "对朋友说：问演唱会门票"},
    {"id": "fun-museum", "category": "娱乐与休闲", "target": "工作人员", "raw": "问博物馆开放时间", "front": "对工作人员说：问博物馆开放时间"},
    {"id": "fun-tour", "category": "娱乐与休闲", "target": "旅行社工作人员", "raw": "订一日游", "front": "对旅行社工作人员说：订一日游"},
    {"id": "fun-hiking", "category": "娱乐与休闲", "target": "朋友", "raw": "约朋友去徒步", "front": "对朋友说：约朋友去徒步"},
    {"id": "fun-picnic", "category": "娱乐与休闲", "target": "朋友", "raw": "提议去野餐", "front": "对朋友说：提议去野餐"},
    {"id": "fun-board-game", "category": "娱乐与休闲", "target": "朋友", "raw": "问有没有桌游", "front": "对朋友说：问有没有桌游"},
    {"id": "fun-karaoke", "category": "娱乐与休闲", "target": "朋友", "raw": "约唱歌", "front": "对朋友说：约唱歌"},
    {"id": "fun-gym-visit", "category": "娱乐与休闲", "target": "前台", "raw": "问健身房能不能单次体验", "front": "对前台说：问健身房能不能单次体验"},
    {"id": "fun-pool-hours", "category": "娱乐与休闲", "target": "工作人员", "raw": "问游泳池开放时间", "front": "对工作人员说：问游泳池开放时间"},
    {"id": "fun-park-events", "category": "娱乐与休闲", "target": "工作人员", "raw": "问公园有什么活动", "front": "对工作人员说：问公园有什么活动"},
    {"id": "fun-class", "category": "娱乐与休闲", "target": "工作人员", "raw": "问有没有兴趣班或体验课", "front": "对工作人员说：问有没有兴趣班或体验课"},
    {"id": "fun-theater", "category": "娱乐与休闲", "target": "工作人员", "raw": "买剧院票", "front": "对工作人员说：买剧院票"},
    {"id": "fun-market", "category": "娱乐与休闲", "target": "当地人", "raw": "问周末市集在哪", "front": "对当地人说：问周末市集在哪"},
    {"id": "fun-nightlife", "category": "娱乐与休闲", "target": "当地人", "raw": "问晚上有什么好去处", "front": "对当地人说：问晚上有什么好去处"},
    {"id": "fitness-membership", "category": "健身与运动", "target": "前台", "raw": "办健身房会员", "front": "对前台说：办健身房会员"},
    {"id": "fitness-hours", "category": "健身与运动", "target": "前台", "raw": "问健身房营业时间", "front": "对前台说：问健身房营业时间"},
    {"id": "fitness-trainer", "category": "健身与运动", "target": "教练", "raw": "请私教", "front": "对教练说：请私教"},
    {"id": "fitness-class", "category": "健身与运动", "target": "前台", "raw": "问团课时间表", "front": "对前台说：问团课时间表"},
    {"id": "fitness-equipment", "category": "健身与运动", "target": "教练", "raw": "问器械怎么用", "front": "对教练说：问器械怎么用"},
    {"id": "fitness-lap", "category": "健身与运动", "target": "救生员", "raw": "问泳道开放", "front": "对救生员说：问泳道开放"},
    {"id": "fitness-run", "category": "健身与运动", "target": "当地人", "raw": "问附近跑步路线", "front": "对当地人说：问附近跑步路线"},
    {"id": "fitness-injury", "category": "健身与运动", "target": "教练", "raw": "运动受伤了怎么办", "front": "对教练说：运动受伤了怎么办"},
    {"id": "fitness-yoga", "category": "健身与运动", "target": "教练", "raw": "约瑜伽课", "front": "对教练说：约瑜伽课"},
    {"id": "fitness-team", "category": "健身与运动", "target": "队长", "raw": "问怎么加入球队", "front": "对队长说：问怎么加入球队"},
    {"id": "fitness-basketball", "category": "健身与运动", "target": "朋友", "raw": "约人打篮球", "front": "对朋友说：约人打篮球"},
    {"id": "fitness-badminton", "category": "健身与运动", "target": "工作人员", "raw": "订羽毛球场地", "front": "对工作人员说：订羽毛球场地"},
    {"id": "fitness-beginner", "category": "健身与运动", "target": "教练", "raw": "问初学者适合什么", "front": "对教练说：问初学者适合什么"},
    {"id": "fitness-shower", "category": "健身与运动", "target": "前台", "raw": "问健身房有没有淋浴", "front": "对前台说：问健身房有没有淋浴"},
    {"id": "family-pickup", "category": "家庭与孩子", "target": "老师", "raw": "接孩子放学", "front": "对老师说：接孩子放学"},
    {"id": "family-enroll", "category": "家庭与孩子", "target": "招生老师", "raw": "给孩子报名学校", "front": "对招生老师说：给孩子报名学校"},
    {"id": "family-parent-teacher", "category": "家庭与孩子", "target": "老师", "raw": "约家长会", "front": "对老师说：约家长会"},
    {"id": "family-homework", "category": "家庭与孩子", "target": "孩子", "raw": "辅导孩子作业", "front": "对孩子说：辅导孩子作业"},
    {"id": "family-babysitter", "category": "家庭与孩子", "target": "中介", "raw": "找临时看孩子的人", "front": "对中介说：找临时看孩子的人"},
    {"id": "family-kid-sick", "category": "家庭与孩子", "target": "老师", "raw": "孩子生病了请假", "front": "对老师说：孩子生病了请假"},
    {"id": "family-dinner", "category": "家庭与孩子", "target": "家人", "raw": "约家庭聚餐", "front": "对家人说：约家庭聚餐"},
    {"id": "family-daycare", "category": "家庭与孩子", "target": "托儿所老师", "raw": "问托儿所", "front": "对托儿所老师说：问托儿所"},
    {"id": "family-kids-park", "category": "家庭与孩子", "target": "家人", "raw": "问附近儿童游乐场", "front": "对家人说：问附近儿童游乐场"},
    {"id": "family-birthday", "category": "家庭与孩子", "target": "孩子", "raw": "给孩子办生日会", "front": "对孩子说：给孩子办生日会"},
    {"id": "family-supplies", "category": "家庭与孩子", "target": "家人", "raw": "买开学用品", "front": "对家人说：买开学用品"},
    {"id": "family-schedule", "category": "家庭与孩子", "target": "孩子", "raw": "问孩子课程表", "front": "对孩子说：问孩子课程表"},
    {"id": "family-swimming", "category": "家庭与孩子", "target": "教练", "raw": "给孩子报游泳课", "front": "对教练说：给孩子报游泳课"},
    {"id": "family-emergency-contact", "category": "家庭与孩子", "target": "老师", "raw": "填紧急联系人", "front": "对老师说：填紧急联系人"},
    {"id": "pet-vet", "category": "宠物", "target": "兽医", "raw": "约宠物医生", "front": "对兽医说：约宠物医生"},
    {"id": "pet-feeding", "category": "宠物", "target": "兽医", "raw": "问宠物一天喂几次", "front": "对兽医说：问宠物一天喂几次"},
    {"id": "pet-walk", "category": "宠物", "target": "兽医", "raw": "问遛狗注意事项", "front": "对兽医说：问遛狗注意事项"},
    {"id": "pet-hotel", "category": "宠物", "target": "宠物店员工", "raw": "找宠物寄养", "front": "对宠物店员工说：找宠物寄养"},
    {"id": "pet-adopt", "category": "宠物", "target": "收容所工作人员", "raw": "问领养宠物流程", "front": "对收容所工作人员说：问领养宠物流程"},
    {"id": "pet-park", "category": "宠物", "target": "当地人", "raw": "问附近宠物公园", "front": "对当地人说：问附近宠物公园"},
    {"id": "pet-allergy", "category": "宠物", "target": "兽医", "raw": "宠物过敏怎么办", "front": "对兽医说：宠物过敏怎么办"},
    {"id": "pet-bath", "category": "宠物", "target": "宠物店员工", "raw": "给宠物洗澡", "front": "对宠物店员工说：给宠物洗澡"},
    {"id": "pet-lost", "category": "宠物", "target": "路人", "raw": "宠物丢了", "front": "对路人说：宠物丢了"},
    {"id": "pet-insurance", "category": "宠物", "target": "保险公司客服", "raw": "问宠物保险", "front": "对保险公司客服说：问宠物保险"},
]

_BY_ID: dict[str, dict[str, str]] = {}
_BY_FRONT: dict[str, dict[str, str]] = {}
_BY_RAW: dict[str, dict[str, str]] = {}
_CATEGORY_ORDER: list[str] = []
for _need in NEEDS:
    _BY_ID[_need["id"]] = _need
    _BY_FRONT.setdefault(_need["front"], _need)
    _BY_RAW.setdefault(_need["raw"], _need)
    if _need["category"] not in _CATEGORY_ORDER:
        _CATEGORY_ORDER.append(_need["category"])


def by_id(need_id: str) -> dict[str, str] | None:
    return _BY_ID.get(need_id)


def by_raw(raw: str) -> dict[str, str] | None:
    return _BY_RAW.get(raw)


def by_front(front: str) -> dict[str, str] | None:
    """按正面匹配：优先完整匹配，也接受去掉“对X说：”前缀后的原始需求。"""
    need = _BY_FRONT.get(front)
    if need:
        return need
    import re
    stripped = re.sub(r"^对.+?说：", "", front)
    return _BY_RAW.get(stripped)


def categories() -> list[dict[str, object]]:
    """按分类返回需求组，保持内置顺序。"""
    grouped: dict[str, list[dict[str, str]]] = {name: [] for name in _CATEGORY_ORDER}
    for need in NEEDS:
        grouped[need["category"]].append(need)
    return [
        {"id": _category_slug(name), "name": name, "needs": grouped[name]}
        for name in _CATEGORY_ORDER
    ]


def _category_slug(name: str) -> str:
    """中文分类名转稳定英文 slug（仅用于前端分组标识）。"""
    mapping = {
        "日常寒暄": "daily-greetings",
        "校园学习": "campus-study",
        "工作职场": "workplace",
        "会议讨论": "meetings",
        "邮件与电话": "email-phone",
        "租房居住": "housing",
        "购物消费": "shopping",
        "餐饮": "dining",
        "交通出行": "transportation",
        "问路与方向": "directions",
        "银行与办事": "banking-services",
        "医疗健康": "health",
        "社交邀约": "social-invitations",
        "情绪与求助": "emotions-help",
        "突发状况": "emergencies",
        "告别与结束": "leave-taking",
        "手机与网络": "phone-internet",
        "快递与物流": "parcel-delivery",
        "面试与求职": "job-interviews",
        "机场与出入境": "airport-travel",
        "娱乐与休闲": "leisure",
        "健身与运动": "fitness-sports",
        "家庭与孩子": "family-kids",
        "宠物": "pets",
    }
    return mapping.get(name, f"cat-{len(mapping)}")


def need_id_for_front(front: str) -> str:
    """内置需求用稳定 id，自定义需求用内容哈希，保证同一句不重复建卡。"""
    need = by_front(front)
    if need:
        return need["id"]
    import hashlib

    return "sp-" + hashlib.sha1(front.encode("utf-8")).hexdigest()[:16]

